### ISSUE TITLE
Directly loading raw CSV file into Python DataViewer

### ISSUE THREAD

**Issue by unidesigner** [EmotiBit/EmotiBit_Biometric_Lib#24]
Is it correct that the current Python DataViewer requires as input the channel that that is generated with the EmotibitDataParser first?
Would it be possible to directly load the raw CSV file which comes from the Emotibit and discover recorded channels etc?

**Comment by nitin710** [comment]
@unidesigner , sorry but this issue slipped our notifications. The best place to ask non-dev  questions on our [forum](http://forum.emotibit.com). That is the best way to reach support.

RE your question, The viewer currently does require parsed data. This is because the file format of the [raw data](https://github.com/EmotiBit/EmotiBit_Docs/blob/master/Working_with_emotibit_data.md#raw-data-format) is different from [parsed](https://github.com/EmotiBit/EmotiBit_Docs/blob/master/Working_with_emotibit_data.md#parsed-data-file-format).

Closing this issue because the issue date is old. If you have more general questions about emotibit, please post on the forum.
